In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



ModuleNotFoundError: No module named 'drawnow'

Hey guys! Hope you are excited to start week 4! 😃

We will go over for loops again this week but a bit harder than last weeks. I will give you a task to start this week just to refresh your memory about for loops since we missed last week 😞

**Task 1**

a. Create a 10 x 10 matrix with ones. Fill the matrix with zeros using a for loop. (note - you will get bonus points if you did not look at last weeks code. Also I recommend using google to get help if you can't remember. In other words try not to look at last weeks code😝)

b. Now create 5 x 5 matrix with zeros. Fill the entire 3rd row with ones. (Only the third row)

c. In parts a and b explain what happens in each iteration.




Now we will go through **<u>functions</u>**. In python we can use 'def' to assign a function. So if we want to assign a function that adds two numbers 'a' and 'b' we can do the following.

In [15]:
a=np.ones([10,10])
b=np.zeros([5,5])
b[2]=1
print (a)
print(b)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
def add(a,b):   #add is the name of the function.
    sum = a + b #here we define the relationship between a and b
    return(sum) #here we define the output

add(11111,11) #now we can use this to add numbers.... 

11122

**Task 2** 

a. Create functions for subtraction, multiplication and division.

In [6]:
def minus(b,c):
    minus=b-c
    return (minus)
minus(89076,789)

def multiply(c,d):
    multiply=c*d
    return(multiply)
multiply(8,9)


72

Now lets try using both functions and for loops in the same example! 

Lets say we want to find the first n fibonnaci numbers(where n is an integer). 

(Also if you don't fibonnacci sequence, it is a sequence such that each number is the sum of the two preceding ones, starting from 0 and 1. So the sequence is 1,1,2,3,5,8,13,21....and it goes on. Also google fibonacci spiral! its pretty interesting!)

So lets write a function to find the first n fibonacci numbers.

In [7]:
def fib(n):
    
    a = 0 #define the first fibonacci number
    b = 1 #define the second fibonacci number
    
    print(a)
    print(b)
    
    for i in range(2,n):
        c = a + b
        a = b
        b = c
        print(c)  
        
fib(100) #now you can find the first fibonacci numbers. Try 100 its actually gonna give you the first 100 fib numbers. I didn't
#try any further but you can try :D

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049
12586269025
20365011074
32951280099
53316291173
86267571272
139583862445
225851433717
365435296162
591286729879
956722026041
1548008755920
2504730781961
4052739537881
6557470319842
10610209857723
17167680177565
27777890035288
44945570212853
72723460248141
117669030460994
190392490709135
308061521170129
498454011879264
806515533049393
1304969544928657
2111485077978050
3416454622906707
5527939700884757
8944394323791464
14472334024676221
23416728348467685
37889062373143906
61305790721611591
99194853094755497
160500643816367088
259695496911122585
420196140727489673
679891637638612258
1100087778366101931
1779979416004714189
2880067194370816120
4660046610375530309
754011380474634642

**Task 3**

a. Write the values of a, b, c in the first 5 iterations of the for loop in the code.

b. Why do I have the range starting from 2 in the for loop? 

c. Write a function that uses an input 'n' and prints out the squares upto n? (if the function name is 'sqr', the output for sqr(4) will be 1,4,9,16)