In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



ModuleNotFoundError: No module named 'drawnow'

Hey guys! Hope you are excited to start week 4! 😃

We will go over for loops again this week but a bit harder than last weeks. I will give you a task to start this week just to refresh your memory about for loops since we missed last week 😞

**Task 1**

a. Create a 10 x 10 matrix with ones. Fill the matrix with zeros using a for loop. (note - you will get bonus points if you did not look at last weeks code. Also I recommend using google to get help if you can't remember. In other words try not to look at last weeks code😝)

b. Now create 5 x 5 matrix with zeros. Fill the entire 3rd row with ones. (Only the third row)

c. In parts a and b explain what happens in each iteration.




Now we will go through **<u>functions</u>**. In python we can use 'def' to assign a function. So if we want to assign a function that adds two numbers 'a' and 'b' we can do the following.

In [15]:
a=np.ones([10,10])
b=np.zeros([5,5])
b[2]=1
print (a)
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
def add(a,b):   #add is the name of the function.
    sum = a + b #here we define the relationship between a and b
    return(sum) #here we define the output

add(11111,11) #now we can use this to add numbers.... 

11122

**Task 2** 

a. Create functions for subtraction, multiplication and division.

Now lets try using both functions and for loops in the same example! 

Lets say we want to find the first n fibonnaci numbers(where n is an integer). 

(Also if you don't fibonnacci sequence, it is a sequence such that each number is the sum of the two preceding ones, starting from 0 and 1. So the sequence is 1,1,2,3,5,8,13,21....and it goes on. Also google fibonacci spiral! its pretty interesting!)

So lets write a function to find the first n fibonacci numbers.

In [ ]:
def fib(n):
    
    a = 0 #define the first fibonacci number
    b = 1 #define the second fibonacci number
    
    print(a)
    print(b)
    
    for i in range(2,n):
        c = a + b
        a = b
        b = c
        print(c)  
        
fib(10) #now you can find the first fibonacci numbers. Try 100 its actually gonna give you the first 100 fib numbers. I didn't
#try any further but you can try :D

**Task 3**

a. Write the values of a, b, c in the first 5 iterations of the for loop in the code.

b. Why do I have the range starting from 2 in the for loop? 

c. Write a function that uses an input 'n' and prints out the squares upto n? (if the function name is 'sqr', the output for sqr(4) will be 1,4,9,16)